# Generated by Django 4.2.29 on 2026-03-10 13:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('status_code', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_unit', models.CharField(choices=[('celsius', 'Celsius (°C)'), ('fahrenheit', 'Fahrenheit (°F)')], default='celsius', max_length=10)),
                ('wind_speed_unit', models.CharField(choices=[('metric', 'm/s'), ('imperial', 'mph')], default='metric', max_length=10)),
                ('time_format', models.CharField(choices=[('12h', '12-hour'), ('24h', '24-hour')], default='24h', max_length=3)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (System)')], default='auto', max_length=10)),
                ('email_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=False)),
                ('alert_threshold', models.CharField(default='moderate', max_length=10)),
                ('default_city', models.CharField(blank=True, max_length=100)),
                ('default_country', models.CharField(blank=True, max_length=100)),
                ('show_map', models.BooleanField(default=True)),
                ('show_air_quality', models.BooleanField(default=True)),
                ('show_alerts', models.BooleanField(default=True)),
                ('auto_refresh', models.BooleanField(default=False)),
                ('refresh_interval', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(360)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('api_source', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='favoritecity',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoritecity',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='search_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weatheralert',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='weatheralert',
            name='instruction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weatheralert',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatheralert',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatheralert',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='weatheralert',
            name='title',
            field=models.CharField(default='General weather alert', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatheralert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='weatheralert',
            name='alert_type',
            field=models.CharField(choices=[('storm', 'Thunderstorm'), ('tornado', 'Tornado'), ('hurricane', 'Hurricane'), ('flood', 'Flood'), ('extreme_temp', 'Extreme Temperature'), ('high_wind', 'High Wind'), ('heavy_snow', 'Heavy Snow'), ('blizzard', 'Blizzard'), ('fog', 'Dense Fog'), ('heat', 'Heat Wave'), ('cold', 'Cold Wave'), ('fire', 'Fire Danger'), ('avalanche', 'Avalanche'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='weatheralert',
            name='severity',
            field=models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('extreme', 'Extreme')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='favoritecity',
            index=models.Index(fields=['user', 'is_active'], name='weather_fav_user_id_5c4c08_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', '-search_date'], name='weather_sea_user_id_bfcce1_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['city_name', 'country'], name='weather_sea_city_na_e9a85f_idx'),
        ),
        migrations.AddIndex(
            model_name='weatheralert',
            index=models.Index(fields=['city_name', 'country'], name='weather_wea_city_na_0d3daf_idx'),
        ),
        migrations.AddIndex(
            model_name='weatheralert',
            index=models.Index(fields=['-start_time'], name='weather_wea_start_t_8a69ad_idx'),
        ),
        migrations.AddIndex(
            model_name='weatheralert',
            index=models.Index(fields=['severity'], name='weather_wea_severit_7a4326_idx'),
        ),
        migrations.AddIndex(
            model_name='weathercache',
            index=models.Index(fields=['cache_key', 'expires_at'], name='weather_wea_cache_k_c65b02_idx'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apilog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['-timestamp'], name='weather_api_timesta_48e79f_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['endpoint', 'status_code'], name='weather_api_endpoin_c10c08_idx'),
        ),
    ]
