# Generated by Django 4.2.29 on 2026-05-07 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0002_apilog_usersettings_weathercache_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('default_location', models.CharField(blank=True, max_length=100)),
                ('home_city', models.CharField(blank=True, max_length=100)),
                ('work_city', models.CharField(blank=True, max_length=100)),
                ('notification_email', models.BooleanField(default=True)),
                ('notification_sms', models.BooleanField(default=False)),
                ('notification_push', models.BooleanField(default=False)),
                ('fcm_token', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('alert_threshold_temp_high', models.FloatField(default=35)),
                ('alert_threshold_temp_low', models.FloatField(default=0)),
                ('alert_threshold_wind', models.FloatField(default=50)),
                ('alert_threshold_rain', models.FloatField(default=20)),
                ('alert_threshold_snow', models.FloatField(default=10)),
                ('alert_threshold_aqi', models.IntegerField(default=150)),
                ('alert_threshold_uv', models.IntegerField(default=8)),
                ('share_weather', models.BooleanField(default=False)),
                ('public_profile', models.BooleanField(default=False)),
                ('total_searches', models.IntegerField(default=0)),
                ('weather_checks', models.IntegerField(default=0)),
                ('alerts_received', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('search', 'Search'), ('view', 'View'), ('share', 'Share'), ('alert', 'Alert Received'), ('favorite_add', 'Add Favorite'), ('favorite_remove', 'Remove Favorite')], max_length=20)),
                ('city_name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('alert', 'Weather Alert'), ('forecast', 'Daily Forecast'), ('system', 'System Update'), ('tip', 'Weather Tip')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
