# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_userprofile_useractivity_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatheralert',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='weatheralert',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
